#!/bin/bash

# Put this file at: .git/hooks/post-checkout
# and make it executable
# You can install it system wide too, see http://stackoverflow.com/a/2293578/685587

PREV_COMMIT=$1
POST_COMMIT=$2

if [[ $PREV_COMMIT == "0000000000000000000000000000000000000000" ]] ; then
    exit
fi

NOCOLOR='\e[0m'
YELLOWCOLOR='\e[30;43m'

if [[ -f composer.lock ]]; then
    DIFF=`git diff --shortstat $PREV_COMMIT..$POST_COMMIT composer.lock`
    if [[ $DIFF != "" ]]; then
        echo -e "${YELLOWCOLOR}composer.lock has changed. You must run composer install$NOCOLOR"
    fi
fi
